# Growth requirements for multiple choice
color_list:
  - Non-flowering
  - Insignificant
  - White
  - Red
  - Orange
  - Yellow
  - Green
  - Blue
  - Lavender
  - Pink
  - Purple
  - Brown

sunlight_list:
  - Full sun
  - Partial shade
  - Full shade

soil_list:
  - Clay
  - Loam
  - Silt
  - Sandy
  - Wide range
  - Well-drained
  - Water-retentive

soil_ph_list:
  - Acidic
  - Neutral
  - Alkaline
  - Wide-range