# Growth requirements for multiple choice
bloom_start:
  - Not applicable
  - January
  - February
  - March
  - April
  - May
  - June
  - July
  - August
  - September
  - October
  - November
  - December
  
bloom_end:
  - Not applicable
  - January
  - February
  - March
  - April
  - May
  - June
  - July
  - August
  - September
  - October
  - November
  - December

color_list:
  - Not applicable
  - Insignificant
  - White
  - Red
  - Orange
  - Yellow
  - Green
  - Blue
  - Lavender
  - Pink
  - Purple
  - Brown

slot:
  - early
  - mid
  - late

sunlight_list:
  - Full sun
  - Partial shade
  - Full shade

soil_list:
  - Clay
  - Loam
  - Silt
  - Sandy
  - Wide range
  - Well-drained
  - Water-retentive

soil_ph_list:
  - Acidic
  - Neutral
  - Alkaline
  - Wide-range